### PR TITLE
add NaN.isNaN()

### PR DESCRIPTION
**Pull request by sonnyp**
My guess would be there is a good reason for it missing from the proposal but just in case...

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
`NaN` is a primitive. `Number.isNaN()` [is in the spec](https://tc39.github.io/ecma262/#sec-number.isnan)

**Comment by jasnell** [comment]
`isNaN()` already works consistently across multiple contexts in Node.js which is the primary use case for these methods. Given that it works consistently already, I saw little reason for a `NaN.isNaN()`

**Comment by sonnyp** [comment]
> I saw little reason for a NaN.isNaN()

Consistency? Not sure it's good enough though.

@chicoxyzzy primitives have properties. `NaN.toString()`

EDIT: I see your point `Number.isNaN()` probably makes more sense.

**Comment by chicoxyzzy** [comment]
@sonnyp primitives can't have any methods. In your example primitive value `NaN` is implicitly converted to `Number` object which has `toString()` method in it's prototype.

**Comment by sonnyp** [comment]
@chicoxyzzy okay, thanks

**Pull request closed without merging**
