### PR TITLE
Add Function.isAsyncFunction

### PR DESCRIPTION
**Pull request by addaleax**

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
how can you check it? technically every function which returns promise is async function. in most cases you can't know statically if function will return promise

**Comment by addaleax** [comment]
(edit: answer to deleted comment)

Yeah, this obviously wouldn’t check whether a function returns a `Promise` but whether it was declared as `async function …`.

And btw, I opened this PR because V8 5.5 comes with `IsAsyncFunction` (which the original list here was based on).

**Comment by chicoxyzzy** [comment]
sorry just deleted my comment second before you posted an answer. I was wrong. you really can check this statically. my bad :)

**Comment by jasnell** [comment]
Going a different direction on this. Async function is covered...

**Pull request closed without merging**
